### ISSUE TITLE
Shrink internal arrays

### ISSUE THREAD

**Issue by JannikGM** [mourner/flatqueue#3]
Currently, once a FlatQueue was filled, it will use a considerable amount of memory, even when the queue is less full (even after a `clear`).

That happens because the FlatQueue itself will only use `this.length` to track the size of the queue, but the `ids` and `values` arrays will never be shrunk again (to match the current `this.length`).

There should be a way to trigger a cleanup of the queue, or it should clean up after itself using some heuristic.

**Comment by mourner** [comment]
Yes, this was done on purpose in #1, but adding a method to trigger release of the storage (e.g. `queue.shrink()`) is a good idea.
